pipeline {
    agent any
  
    stages{
        stage('database container') {
            steps {
                sh 'sudo docker container rm -f mysql'
                sh 'sudo docker container run -d --name mysql -e MYSQL_ROOT_PASSWORD=P@55word -p 3306:3306 mysql:latest'
             }
          }
        stage('Remove Existing Backend Image') {
            steps {
                script {
                    sh 'sudo docker rmi -f backend:latest'
                }
            }
        }
        stage('Docker build') {
            steps {
                #sh 'sudo docker rmi -f backend'
                sh 'cd /lms-java/LMS-BE && sudo docker build -t backend .'
            }
          }
        stage('Docker container') {
            steps {
                sh 'sudo docker container rm -f be'
                sh 'sudo docker container run -dt --name be -p 8080:8080 backend'
            }
        }
        stage('Docker') {
            steps {
                sh 'echo deployment done'
               }
          }
    }
}
