pipeline {
    agent any

    environment {
        MYSQL_ROOT_PASSWORD = 'P@55word'
    }

    stages {
        stage('Build Backend Docker Image') {
            steps {
                script {
                    // Change to the backend directory
                    dir('/var/lib/jenkins/workspace/BE-lms/LMS-BE') {
                        // Build Docker image for the backend
                        sh 'docker build -t backend-image .'
                    }
                }
            }
        }

        stage('Run MySQL Container') {
            steps {
                script {
                    // Run MySQL Docker container
                    sh "docker run -d --name mysql-container -p 3036:3036 -e MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD} mysql:latest"
                }
            }
        }

        stage('Run Backend Container') {
            steps {
                script {
                    // Run Backend Docker container
                    sh 'docker run -d --name backend-container -p 8080:8080 --link mysql-container:mysql backend-image'
                }
            }
        }
    }

    post {
        always {
            // Cleanup: Stop and remove containers
            script {
                sh 'docker stop backend-container mysql-container'
                sh 'docker rm backend-container mysql-container'
            }
        }
    }
}
