pipeline {
    agent any

    stages {
        stage('Build MySQL Docker Image') {
            steps {
                script {
                    // Build MySQL Docker image
                    docker.build('custom-mysql-image', '-f Dockerfile-mysql .')
                }
            }
        }

        stage('Create MySQL Container') {
            steps {
                script {
                    def mysqlContainerExists = sh(script: 'docker ps -a --format "{{.Names}}" | grep -q "mysql1"', returnStatus: true)

                    if (mysqlContainerExists == 0) {
                        echo "MySQL container 'mysql1' already exists. Skipping container creation."
                    } else {
                        // Create MySQL Docker container
                        docker.image('custom-mysql-image').withRun('-d --name mysql1 -e MYSQL_ROOT_PASSWORD=P@55word')
                    }
                }
            }
        }
    }
}
