pipeline {
    agent any
    stages {
        stage('Build') {
            steps {
                sh 'cd lmsv1 && docker build -t fe .'
                }
            }
        stage('Run') {
            steps {
                 sh 'docker run -d --name lms-fe -p 8080:8080 fe'
            }
        }
    }
 }
