pipeline {
    agent any
    stages {
        stage('remove docker container'){
            steps{
                sh 'docker rm -f lmsfe2'
            }
        }
        stage('Build') {
            steps {
                sh 'cd lms-fe/lmsv1 && docker build -t fe .'
                }
            }
        stage('Run') {
            steps {
                 sh 'docker run -d --name lms-fe2 -p 80:80 fe'
            }
        }
    }
 }
